services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable
    container_name: wolf-${INSTANCE}
    restart: unless-stopped
    ports:
      - "${BIND_IP}:47984:47984/tcp"
      - "${BIND_IP}:47989:47989/tcp"
      - "${BIND_IP}:47999:47999/udp"
      - "${BIND_IP}:48010:48010/tcp"
      - "${BIND_IP}:48100:48100/udp"
      - "${BIND_IP}:48200:48200/udp"
    volumes:
      - /etc/wolf-${INSTANCE}:/etc/wolf:rw
      - /run/podman/podman.sock:/var/run/docker.sock:rw
      - /dev/:/dev/:rw
      - /run/udev:/run/udev:rw
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/uhid
    device_cgroup_rules:
      - "c 13:* rmw"